In [3]:
import pandas as pd

data2 = pd.read_csv("responses-2.csv")
data2.head()

,#,What are you?,NONE,vegan,salmon,pig,cow,+1 or +3,How likely is this +1/3 going to donate?,Contact,Mobile Phone,Email number,"Time is NOT money, NOT today.",Your web in the net,Likeliness to NOT do this form again,Repeat for a friend,Start Date (UTC),Submit Date (UTC),Network ID,Tags
0,phyvlis3ij6m0penvjphyvsfaqf9g2j9,SPONSER,NONE,NaN,NaN,NaN,NaN,NaN,NaN,email,NaN,danny.pinkney@gmail.com,1700,NaN,3,1,2023-01-01 18:19:36,2023-01-01 18:21:05,1ec66fab85,NaN
1,tbcul4yc95vhgu4jtbcthc2wdgg05js2,CREATOR,NaN,NaN,NaN,NaN,NaN,'+none,NaN,email,NaN,s2306209@ed.ac.uk,1700,NaN,0,0,2023-01-01 13:36:59,2023-01-01 13:38:10,551b8b49a4,NaN
2,bjf18ijy43jbufc2y5txtcbjf18ivvvu,SPONSER,NaN,NaN,salmon,NaN,cow,NaN,NaN,email,NaN,ms.mariamkhan@gmail.com,1700,NaN,0,1,2023-01-01 09:13:33,2023-01-01 09:14:33,0458e5380d,NaN
3,iv4jxpcisshoopmiv4jxp7hg2dihl15v,SPONSER,NaN,NaN,salmon,NaN,NaN,NaN,NaN,email,NaN,donadristi@gmail.com,100,NaN,8,0,2023-01-01 01:26:03,2023-01-01 01:27:01,d9b5b39fa0,NaN
4,85e0slvnljib2j5v8ypf85e0swz2jgh7,SPONSER,NaN,vegan,salmon,pig,cow,NaN,NaN,email,NaN,s1915333@ed.ac.uk,100,https://artgala.co.uk,0,0,2023-01-01 01:18:31,2023-01-01 01:19:23,6914726b5f,NaN